FROM centos:7
LABEL maintainer "DI GREGORIO Nicolas <ndigrego@ndg-consulting.tech>"

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm' \
    APPUSER='mtgapi' \
    APPUID='10022' \
    APPGID='10022' \
    PY_VERSION='35'

### Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    chmod 1777 /tmp && \
    . /usr/local/bin/docker-entrypoint-functions.sh && \
    MYUSER="${APPUSER}" && \
    MYUID="${APPUID}" && \
    MYGID="${APPGID}" && \
    ConfigureUser && \
    yum-config-manager --add-repo /tmp/custom.repo && \
    yum install -y \
      centos-release-scl.noarch \
    && \
    yum update -y && \
    yum install -y \
      bash \
      rh-python${PY_VERSION}-python \
      pcre \
    && \
    yum install -y \
      wget \
      rh-python35-python-devel \
      gcc \
      git \
      pcre-devel \
    && \
    . /opt/rh/rh-python${PY_VERSION}/enable && \
    ln -s /opt/rh/rh-python${PY_VERSION}/enable /etc/profile.d/docker-python.sh && \
    git clone --depth 1 https://github.com/digrouz/mtgapi /opt/mtgapi && \
    pip3 install --no-cache-dir --upgrade \
      setuptools \
      pip \
    && \
    pip3 install --no-cache-dir --upgrade -r /opt/mtgapi/requirements.txt && \
    yum history -y undo last && \
    mkdir /docker-entrypoint.d && \
    chmod +x /usr/local/bin/docker-entrypoint.sh && \
    yum clean all && \
    ln -snf /usr/local/bin/docker-entrypoint.sh /docker-entrypoint.sh && \
    rm -rf /tmp/* \
           /opt/mtgapi/.git* \
           /var/cache/yum/*  \
           /var/tmp/*
    
### Expose volumes
#VOLUME []

### Expose ports
EXPOSE 6666 6667

### Running User: not used, managed by docker-entrypoint.sh
#USER mtgapi

### Start mtgapi
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["mtgapi"]
